llm:
  model: "gpt-4o"
  temperature: 0.3
  max_tokens: 1000

rules:
  STYLE-001: high
  STYLE-002: medium
  NULL-001: high
  SEC-001: high
  EXC-001: medium
  DS-001: medium
  OOP-001: high
  OOP-002: medium
  OOP-003: low
  OOP-004: high

limits:
  max_lines: 1000
  timeout_seconds: 120
